version: "3.9"

services:
  checkmk:
    container_name: checkmk
    image: checkmk/check-mk-raw:latest
    restart: unless-stopped
    hostname: checkmk
    network_mode: bridge
    environment:
      - TZ=Europe/Warsaw
      - CMK_PASSWORD=your_password
    ports:
      - "8080:5000/tcp"   # Web UI
      - "8000:8000/tcp"   # Livestatus
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    volumes:
      - /your_path/docker/checkmk:/omd/sites
    deploy:
      resources:
        limits:
          memory: 15866M
        reservations:
          memory: "67108864"
