version: "3.9"

services:
  firefox:
    container_name: firefox
    image: lscr.io/linuxserver/firefox:latest
    restart: unless-stopped
    hostname: firefox
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - FIREFOX_CLI=https://www.linuxserver.io/
    ports:
      - "3005:3000/tcp"   # Główny interfejs Firefox
      - "3006:3001/tcp"   # Dodatkowy port
    volumes:
      - /your_path/docker/firefox/config:/config
    security_opt:
      - seccomp:unconfined
    shm_size: "1073741824"
    deploy:
      resources:
        limits:
          memory: 15866M
        reservations:
          memory: "67108864"