services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000 # User ID the container belongs to
      - PGID=1000 # Group ID the container belongs to
      - TZ=Etc/UTC
      # Main application encryption key in base64 format
      - APP_KEY=base64:xxxxxxxxx
      # Domain under which the container is accessible
      - APP_URL=https://kontener.speedtest-tracker.com
      # SQLite database connection
      - DB_CONNECTION=sqlite
      # Test schedule: tests at 0:00, 4:00, 8:00, 14:00, 21:00 every day
      - SPEEDTEST_SCHEDULE=0 4,8,14,21 * * *
      # Empty - default servers
      - SPEEDTEST_SERVERS=
      - DISPLAY_TIMEZONE=Europe/Warsaw
      - PRUNE_RESULTS_OLDER_THAN=0
     # Container configuration files location
    volumes:
      - /docker/speedtest-tracker/data:/config
    ports:
      - 8099:80 # Container Web UI : port on which the container runs
    # Public DNS addresses added due to the server's MeshVPN DNS
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
    # Do not start Speedtest until the Apprise container is up
    depends_on:
      - apprise-api

  # Container for handling notifications
  apprise-api:
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: apprise-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    restart: unless-stopped
