version: "3.9"
services:
  vaultwarden:
    image: vaultwarden/server:testing
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.domanin.com" # The URL (domain) of your Vaultwarden instance 
      SSO_ENABLED: "true" # Whether SSO login should be active
      SSO_ONLY: "true"  # Disables Master Password / email login
      SSO_SIGNUPS_MATCH_EMAIL: "true"  # Links existing accounts by email
      SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: "false" # Controls whether a user with an unknown email can log in after SSO verification
      SSO_AUTHORITY: "https://authentik.company/application/o/vaultwarden/" # The URL (endpoint) of the SSO/OIDC service
      SSO_CLIENT_ID: # Client application ID registered in the SSO/OIDC service 
      SSO_CLIENT_SECRET: # Secret key authenticating Vaultwarden against the SSO/OIDC server
      SSO_SCOPES: "openid email profile offline_access" # Permission scopes according to the OIDC protocol 
      SSO_OIDC_REDIRECT_URL: "https://vaultwarden.domanin.com/sso/oidc-signin" # Specifies the exact URL to which Vaultwarden should redirect the user after authentication by the external SSO provider
      SSO_ROLES_ENABLED: "false" # Allows mapping roles from SSO to Vaultwarden accounts
      SSO_PKCE: "true" # Enables the PKCE (Proof Key for Code Exchange) mechanism
      SSO_DEBUG_TOKENS: "false" # If true, enables printing OIDC/SSO tokens in Vaultwarden logs for debugging
    volumes:
      - /your_path/docker/vaultwarden:/data
    ports:
      - 10380:80
