services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.7
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /your_path/docker/jellyfin/config:/config
      - /path/to/yours/movies:/data/movies
      - /path/to/yours/series:/data/series
    ports:
      - 8096:8096      # HTTP Web UI and HTTP streaming
      - 8920:8920      # HTTPS Web UI and HTTPS streaming (optional)
      - 7359:7359/udp  # Auto-discovery for local clients (optional)
      - 1900:1900/udp  # DLNA/UPnP service discovery (optional)
    restart: unless-stopped
