version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "8443:9443" # Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /your_path/docker/portainer:/data
