duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    restart: unless-stopped
    environment:
      - PUID=0  # root ID
      - PGID=0  # root group
      - TZ=Europe/Warsaw
      - SETTINGS_ENCRYPTION_KEY=
      - DUPLICATI__WEBSERVICE_PASSWORD=
    volumes:
      # Configuration files location
      - /docker/duplicati:/config
      
      # Source files to backup, visible in Duplicati under /source
      # Read-Only for security
      - /docker:/source:ro
      
      # Finished backups location
      - /serwer/backups:/backups
    ports:
      - 8200:8200 # Web UI
