version: "3.9"

services:
  db:
    container_name: nextcloud-db
    image: mariadb:11
    restart: unless-stopped
    hostname: nextcloud-db
    network_mode: bridge
    environment:
      - MYSQL_DATABASE=mysql_database_name
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_ROOT_PASSWORD=mysql_root_password
      - MYSQL_USER=mysql_user
      - TZ=Europe/Warsaw
    volumes:
      - /your_path/docker/nextcloud-db:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 15866M
        reservations:
          memory: "67108864"

  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud:latest
    restart: unless-stopped
    hostname: nextcloud
    network_mode: bridge
    depends_on:
      - db
      - redis
    environment:
      - MYSQL_DATABASE=mysql_database_name
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_USER=mysql_user
      - PUID=1000
      - PGID=1000
      - REDIS_HOST=redis
      - TZ=Europe/Warsaw
    ports:
      - "8888:80/tcp"        # Nextcloud Web UI
    volumes:
      - /your_path/docker/nextcloud:/config
      - /external_storage:/external
    deploy:
      resources:
        limits:
          memory: 15866M
        reservations:
          memory: "67108864"

  redis:
    container_name: nextcloud-redis
    image: redis:7-alpine
    restart: unless-stopped
    hostname: nextcloud-redis
    network_mode: bridge
    deploy:
      resources:
        limits:
          memory: 15866M
        reservations:
          memory: "67108864"

networks:
  default:
    name: nextcloud_nextcloud-net
    driver: bridge
