services:
  collabora:
    image: collabora/code:latest
    container_name: collabora_code
    restart: unless-stopped
    ports:
      - "9980:9980" # Web UI 
    environment:
      # Allows connection to the Collabora instance
      - domain=all 
      - username=
      - password=
      # Disable SSL inside the container (required with Nginx Proxy Manager)
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    cap_add:
      # Allows the container to create special device files
      - MKNOD 
      # Necessary for mounting operations and file system management inside the container
      - SYS_ADMIN 
    # Allocate a pseudo-TTY to the container
    tty: true 
    extra_hosts:
      # Map the domains under which the container is accessible to the server address
      # because the server is behind a NAT, these entries force local domain resolution
      - "nextcloud.example:192.168.x.x"
      - "collabora.example:192.168.x.x"
