services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Warsaw
      - GOOGLE_API_KEY=
    ports:
      - "1880:1880" # Web UI
    networks:
      - node-red-net
    # Running as root (0:0) is required so that node-red
    # can manage Docker and read system logs without "Permission Denied" errors.
    user: "0:0"
    volumes:
      # Node-RED configuration files location, available under /data in the container
      - /docker/node-red/data:/data
      
      # Mapping the Docker system socket, access to control Docker
      - /var/run/docker.sock:/var/run/docker.sock
      
      # Access to system logs (for reading and backups)
      # Mapping host logs to the /host_logs folder inside the container
      - /var/log:/host_logs:ro

networks:
  node-red-net:
