services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    # Domain under which the container is accessible : IP of the host server
    extra_hosts:
      - "xx.example.com:192.168.x.x"
    restart: unless-stopped
    volumes:
    # Docker configuration files location. /app/data is accessible inside the container
      - /docker/uptime-kuma/data:/app/data
    # Map the Docker system socket
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001" # Container Web UI
