services:
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    command: daemon # Ignore labels, read one main configuration file
    restart: always
    environment:
      - TZ=Europe/Warsaw
    volumes:
      # Map the Docker socket into the Ofelia container
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker:/host_docker
      # Map the ini file location to where Ofelia expects it
      - /docker/ofelia/config.ini:/etc/ofelia.conf
